# Generated by Django 5.0.1 on 2024-01-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('100 to 1000', '100 to 1000'), ('1000 to 2000', '1000 to 2000'), ('2000 to 3000', '2000 to 3000'), ('3000 to 4000', '3000 to 4000'), ('4000 to 5000', '4000 to 5000')], max_length=200)),
            ],
        ),
    ]
