# Generated by Django 5.0.1 on 2024-01-19 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothApp', '0003_alter_product_created_date_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothApp.product')),
            ],
        ),
    ]
