# Generated by Django 5.0.1 on 2024-02-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothApp', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('Images', models.ImageField(upload_to='orderimg')),
                ('quantity', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothApp.order')),
            ],
        ),
    ]
