# Generated by Django 5.0.1 on 2024-02-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothApp', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
